# Generated by Django 3.2.9 on 2021-11-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date_de_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='date_de_publication',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texte',
        ),
    ]
